# .streamlit/config.toml

[theme]
# The primary accent color for interactive elements.
primaryColor = "#7792E3"

# Background color for the main content area.
backgroundColor = "#0E1117"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#283046"

# Color of text in the main content area.
textColor = "#FFFFFF"

# Font family for all text in the app.
# Can be "serif", "sans serif", or "monospace".
font = "sans serif"